Minimum-Number-Of-People-In-The-Lobby-To-Vote: 2
Block-Commands: false
Auto-Start-Players: 4
Auto-Start-Time: 60
Minimum-Players-To-Start: 2
Percent-Of-Votes-Needed-To-Start: 66
Time-Limit-Seconds: 600
Leaderboard-Print-Limit: 5
Debug-Mode: false
MySQL:
  Enable: false
  Address: localhost
  Port: 3306
  Database: Minecraft
  Username: Admin
  Password: Password